version: "3.8" # 버전을 명시합니다.

services:
  jangwon_nginx:
    image: nginx:stable-alpine
    container_name: jangwon_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
      - ./.cert/cert.pem:/etc/nginx/.cert/cert.pem
      - ./.cert/key.pem:/etc/nginx/.cert/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - jangwon_frontend
      - jangwon_backend_01
      - jangwon_backend_02
      - jangwon_minio
    networks:
      - jangwon_networks

  jangwon_frontend:
    container_name: jangwon_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - "3000:3000"
    depends_on:
      - jangwon_backend_01
      - jangwon_minio
    stdin_open: true
    tty: true
    networks:
      - jangwon_networks

  jangwon_backend_01:
    container_name: jangwon_backend_01
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/backend
    env_file:
      - backend/.env
    command: npm run start:prod
    ports:
      - "8000:8000"
    depends_on:
      - jangwon_postgres
      - jangwon_redis
      - jangwon_minio
    networks:
      - jangwon_networks

  jangwon_backend_02:
    container_name: jangwon_backend_02
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/backend
    env_file:
      - backend/.env
    command: npm run start:prod
    ports:
      - "8001:8000"
    depends_on:
      - jangwon_postgres
      - jangwon_redis
    networks:
      - jangwon_networks

  jangwon_postgres:
    container_name: jangwon_postgres
    image: postgres:latest
    restart: always
    env_file:
      - backend/docker.env
    ports:
      - "5432:5432"
    networks:
      - jangwon_networks

  jangwon_redis:
    container_name: jangwon_redis
    image: redis:alpine
    restart: always
    env_file:
      - ./backend/docker.env
    ports:
      - "6379:6379"
    networks:
      - jangwon_networks

  jangwon_minio:
    container_name: jangwon_minio
    image: docker.io/bitnami/minio:2022
    env_file:
      - ./backend/docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - jangwon_networks

networks:
  jangwon_networks: # 이름 수정
    driver: bridge