services:
  jangwon_nginx:
    image: nginx:stable-alpine
    container_name: jangwon_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
      - ./.cert/cert.pem:/etc/nginx/.cert/cert.pem
      - ./.cert/key.pem:/etc/nginx/.cert/key.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - jangwon_backend_01
      - jangwon_backend_02
    networks:
      - jangwon-networks

  jangwon_backend_01:
    container_name: jangwon_backend_01
    build:
      dockerfile: Dockerfile
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - backend/.env
    command: npm run start:dev
    ports:
      #      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "8000:8000"
    depends_on:
      - jangwon_postgres
      - jangwon_redis
      - jangwon_minio
    networks:
      - jangwon-networks

  jangwon_backend_02:
    container_name: jangwon_backend_02
    build:
      dockerfile: Dockerfile
      context: backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - backend/.env
    command: npm run start:dev
    ports:
      #      - "${BACKEND_02_PORT}:${BACKEND_PORT}"
      - "8001:8000"
    depends_on:
      - jangwon_postgres
      - jangwon_redis
    networks:
      - jangwon-networks

  jangwon_postgres:
    container_name: jangwon_postgres
    image: postgres:latest
    restart: always
    env_file:
      - backend/docker.env
    ports:
      #      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      - "5432:5432"
    networks:
      - jangwon-networks

  jangwon_redis:
    container_name: jangwon_redis
    image: redis:alpine
    restart: always
    env_file:
      - ./backend/docker.env
    ports:
      #      - "${REDIS_PORT}:${REDIS_PORT}"
      - "6379:6379"
    networks:
      - jangwon-networks

  jangwon_minio:
    #    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: jangwon_minio
    image: docker.io/bitnami/minio:2022
    #    command: server --address ":9000" --console-address ":9001" /data
    #    volumes:
    #      - ./minio_storage:/data
    env_file:
      - backend/docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - jangwon-networks

networks:
  jangwon-networks:
    driver: bridge